### ISSUE TITLE
Provide a standard public domain license file

### ISSUE THREAD

**Issue by jcastle** [GSA/open-gsa-redesign#106]
Copied over from https://github.com/GSA/GSAOpenSourcePolicy/issues/2 as that repo is now for historical purposes only with the new https://open.gsa.gov/code/ content.

---

As a product owner, I want a standard public domain license file so that I can either copy it to my product's source code repository or link to it.

This would be useful for the Code.gov "license" field, which is required to be a URL. Some projects may not have a license file accessible at a URL. By providing a standard public domain license file that applies to most projects, they can simply link to it. We would need to ensure that this file does not move (or if it moves, we provide a HTTP redirect), so that the license URLs submitted to Code.gov stay valid.

Not sure if this is the correct location for such a license file. Maybe open.gsa.gov, usa.gov, or code.gov?

**Comment by saracope** [comment]
@jcastle Do you have this license file? I can post it here.

**Comment by jcastle** [comment]
https://github.com/GSA/open-source-policy/blob/master/LICENSE.md

**Comment by saracope** [comment]
Ok, that's the same license I'm using here. Do you want to point to it or create a separate file just for other folks to use?
https://github.com/GSA/open-gsa-redesign/blob/dev/LICENSE.md

**Comment by saracope** [comment]
Closing out per convo with Joe. We're good to go on this for now.
