### ISSUE TITLE
Add Acquisition Gateway APIs

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/open-gsa-redesign#108]
Add Acquisition Gateway APIs to the open.gsa.gov/api

Here is the link that should be included on it:

https://hallways.cap.gsa.gov/docs/#/api

**Comment by saracope** [comment]
Is there any add'l info for the description?

**Comment by KehindeOgundolie** [comment]
@rdgsa Hey, I'd be happy to work on this for you. I will just need a 2 - 3 sentence description on the API.

**Comment by KehindeOgundolie** [comment]
@rdgsa Can you provide some clarification on the issue above when you get the time?

**Comment by rdgsa** [comment]
After reviewing the doco, it appears that calling these APIs gets 403 forbidden. So it is not clear to me if this is intended for public use.

I suggest that a point of contact be identified for this API and request they provide information to list it on the directory in the format:
title:
description: (including the intended audience and how credentials are provisioned)
URL:

**Comment by Ryandaydev** [comment]
This is done.
