### ISSUE TITLE
Add a public forum for the public to request new APIs

### ISSUE THREAD

**Issue by rdgsa** [GSA/open-gsa-redesign#112]
From the 5/18/2017 API working group:

Could we add to https://open.gsa.gov/api/ a public forum where we ask people what other APIs  they would like from GSA, a la https://github.com/usedgov/API-Program/issues/1 (linked from their tech hub - ed.gov/developer) ? 
Potential call to action on open.gsa.gov/api
Go to an issue on GSA APIs
Philip Ashlock can also collaborate with existing channels through data.gov

**Comment by jcastle** [comment]
Did this here, https://github.com/GSA/GSA-APIs/issues/47.

**Comment by gbinal** [comment]
Agreed - looks like that does the job perfectly.  

I'll go ahead and close this issue, barring any objections.
