### ISSUE TITLE
Redirect gsa.gov/developers to open.gsa.gov

### ISSUE THREAD

**Issue by jcastle** [GSA/open-gsa-redesign#114]
Right now it goes to the code base for the open.gsa.gov site.  Should just go to the open.gsa.gov site itself.

**Comment by gbinal** [comment]
This is still worth doing.  Would it help if I filed an IT service desk ticket requesting this or should we ask the www.gsa.gov content team to help?

**Comment by saracope** [comment]
Yeah, it requires a service ticket.

**Comment by gbinal** [comment]
Alrighty - I've created a request.
