### ISSUE TITLE
SAM.gov Opportunities Public API ignores short NAICS codes (< 6 digits)

### ISSUE THREAD

**Issue by dpdearing** [GSA/open-gsa-redesign#1176]
The `ncode` request parameter for the SAM.gov Get Opportunities Public API appears to _only_ accept 6-digit codes.

The documentation at https://open.gsa.gov/api/get-opportunities-public-api/#get-opportunities-request-parameters says that the `ncode` parameter is:

> NAICS Code. This code is maximum of 6 digits

However, providing 4-digit prefixes does not return any results.  For example, using NAICS code **541715** will return results:

https://api.sam.gov/opportunities/v2/search?limit=100&postedFrom=03/15/2024&postedTo=03/22/2024&api_key={API_KEY}&active=true&ptype=s,r,p,o,k&ncode=541715

But using the 4-digit NAICS code prefix **5417** does not return any results:

https://api.sam.gov/opportunities/v2/search?limit=100&postedFrom=03/15/2024&postedTo=03/22/2024&api_key={API_KEY}&active=true&ptype=s,r,p,o,k&ncode=5417

This is different behavior from how the NAICS Code search filter behaves at https://sam.gov/search and seems unintentional given how the documentation says that valid codes are a "maximum of 6 digits" and not strictly 6 digits.

**Comment by jfredrickson** [comment]
Hi @dpdearing, please report issues with the SAM APIs or their documentation via an incident ticket or live chat over at [FSD](https://www.fsd.gov).
