### ISSUE TITLE
Unable to reach exclusions API in api-alpha.sam.gov

### ISSUE THREAD

**Issue by rishikv** [GSA/open-gsa-redesign#1231]
I am from Veteran affairs loan guaranty program integrating with exclusions V3 API. From last 10 days we are not able to reach api-alpha.sam.gov and getting the below error. Can you please immediately look into this issue as this is blocking our testing effort for our go live date in july. 

The request URL
https://api-alpha.sam.gov/entity-information/v4/exclusions?includeSections=exclusionDetails&api_key={{api_key}}&exclusionName=[Larry Jones]&ssnOrTinOrEin=<tin>

<!DOCTYPE html>

<html>

**Comment by jfredrickson** [comment]
Please refer to the API documentation for [support contact information](https://open.gsa.gov/api/exclusions-api/#contact-us).

**Comment by rishikv** [comment]
[exclusion-api.json](https://github.com/user-attachments/files/15569760/exclusion-api.json)
There is no POST operation for exclusions API. When i send curl with POST for a federal system account i am getting the below error

curl --location --globoff --request POST 'https://api-alpha.sam.gov/entity-information/v4/exclusions?ssnOrTinOrEin=470145390&api_key=<apiKey>&includeSections=exclusionDetails&exclusionName=[Larry%20Jones]' \
--header 'x-api-key: <apiKey>' \
--header 'Authorization: Basic <Auth info>

Response
{
    "timestamp": "2024-06-04T20:01:56.516+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/sam/v4/exclusions"
}

For the Same Curl with GET getting below error
{
    "timestamp": "2024-06-04 20:04:29.19",
    "message": "Error In Creating Data",
    "type": "Invalid input",
    "errorCode": "PRM",
    "transaction_id": "712c4e38-fb20-4ca7-acb0-c4741fc1e5c4"
}
