### ISSUE TITLE
Cant do a POST on api-alpha.sam.gov with ssnOrTinOrEin for exclusions API

### ISSUE THREAD

**Issue by rishikv** [GSA/open-gsa-redesign#1232]
[exclusion-api.json](https://github.com/user-attachments/files/15569955/exclusion-api.json)
There is no POST operation for exclusions API. When i send curl with POST for a federal system account (omitted base auth and apikey in the curl)i am getting the below error. Is there a dummy or mock TIN or exclusion name i can use and test see if i am getting the response

- the system Account ID: VAVHB
- API Key is active, and has read sensitive/read FOUO permission
- parameters attached

curl --location --globoff --request POST 'https://api-alpha.sam.gov/entity-information/v4/exclusions?ssnOrTinOrEin=470145390&api_key=<apiKey>&includeSections=exclusionDetails&exclusionName=[Larry%20Jones]' \
--header 'x-api-key: <apiKey>' \
--header 'Authorization: Basic <Auth info>

Response
{
    "timestamp": "2024-06-04T20:01:56.516+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/sam/v4/exclusions"
}

For the Same Curl with GET getting below error
{
    "timestamp": "2024-06-04 20:04:29.19",
    "message": "Error In Creating Data",
    "type": "Invalid input",
    "errorCode": "PRM",
    "transaction_id": "712c4e38-fb20-4ca7-acb0-c4741fc1e5c4"
}

**Comment by jfredrickson** [comment]
@rishikv, please refer to the API documentation for [support contact information](https://open.gsa.gov/api/exclusions-api/#contact-us). This repo and its issues are for the [open.gsa.gov](https://open.gsa.gov) website, not the Exclusions API.
