### ISSUE TITLE
Add DSS APIs to the GSA API Directory

### ISSUE THREAD

**Issue by neelmadhavsphadke** [GSA/open-gsa-redesign#129]
We've built APIs for applications & business processes to leverage the Digital Signature capabilities as REST APIs.

We've also created out API documentation based on the proposed Github based API documentation.

Please let us know what information is needed and we'll share that accordingly.

**Comment by KehindeOgundolie** [comment]
@neelmadhavsphadke Can I get a link to your documentation please?

**Comment by neelmadhavsphadke** [comment]
https://gsa.github.io/DSSAPIDocumentation/api-docs/



Thanks & regards,
{
   "name" : "Neel Phadke",
   "role" : "Enterprise Solutions Architect",
   "phone" : "5715278443",
   "location" : "1800 F St NW Washington DC 20405",
   "about us" :
    {
        "team" : "DSS EDMS"
        "team email" : "dssteam@gsa.gov",
        "learn more" : "https://e07r7m-dsstest.gsa.gov/DSSUI/"
    }
}

**Comment by KehindeOgundolie** [comment]
I am working on this

**Comment by neelmadhavsphadke** [comment]
Thank you.

Thanks & regards,
{
   "name" : "Neel Phadke",
   "role" : "Enterprise Solutions Architect",
   "phone" : "5715278443",
   "location" : "1800 F St NW Washington DC 20405",
   "about us" :
    {
        "team" : "DSS EDMS"
        "team email" : "dssteam@gsa.gov",
        "learn more" : "https://e07r7m-dsstest.gsa.gov/DSSUI/"
    }
}

**Comment by KehindeOgundolie** [comment]
@saracope Can you merge the pull request on your end please?
