### ISSUE TITLE
Need a new featured dataset

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/open-gsa-redesign#204]
The social media registry on the [open data page](https://open.gsa.gov/data/) links to a decommissioned site.

We should rotate these for a few new items from data.gov.

**Comment by Ryandaydev** [comment]
@jfredrickson5 @CinnyaSm

**Comment by jfredrickson5** [comment]
Will update to this URL: https://usdigitalregistry.digitalgov.gov/

**Comment by jfredrickson5** [comment]
File to update: [data.yml](https://github.com/GSA/open-gsa-redesign/blob/master/_data/data.yml)

Content should be:
Title: U.S. Digital Registry
Description: The U.S. Digital Registry is an official source of information about federal government social media accounts.
Link: https://usdigitalregistry.digitalgov.gov/
