### ISSUE TITLE
Using list inside a table

### ISSUE THREAD

**Issue by altrine** [GSA/open-gsa-redesign#240]
I want to display a list of error messages inside a table. To do that when I use ordered list markdown inside a table, its not working. Currently I am using it as below.

1. some description <br /> 2. another description

**Comment by jfredrickson5** [comment]
I'm not sure if that's possible in pure Markdown. But what you could do is embed HTML inside the table, or just use a pure HTML table.

Example of embedded HTML in a Markdown table:

|Heading|
|-|
|<ol><li>one</li><li>two</li><li>three</li></ol>|

```
| Heading |
| ------- |
| <ol><li>one</li><li>two</li><li>three</li></ol> |
```

**Comment by altrine** [comment]
yes I can always add regular html list
