### ISSUE TITLE
Some buttons not working on IE 11

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/open-gsa-redesign#254]
On the API page, when a user clicks "View API Documentation" in IE 11, the page is not displayed.

This is also true of the Data page.

**Comment by Ryandaydev** [comment]
The "buttons" that work correctly use `<div class="usa-button-block">`

The "buttons" that don't are `<button class="usa-button-gray">`

**Comment by Ryandaydev** [comment]
Some info on buttons in USWDS: https://designsystem.digital.gov/components/buttons/

**Comment by jfredrickson5** [comment]
Based on the USWDS implementation guide, I'd say try a styled `a` link without having a `button` element at all.
