### ISSUE TITLE
Hide contact us email on bottom of API docs pages

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/open-gsa-redesign#257]
The Contact Us for each API doc should be specific to the API.

Having the additional contact at the bottom of the page (which goes to cto@gsa.gov) may be confusing for users.

Find a method to hide or otherwise exclude this contact on API pages only.

**Comment by jfredrickson5** [comment]
I'd like to avoid making exceptions to the common layout if possible. Have we gotten cto@gsa.gov emails intended for an API team? Maybe we can add clarification for one or both of the "contact us" areas.

Possible changes, other ideas welcome:

* Rename the footer "Contact Us" heading to "Contact GSA"
* Rename the footer "Email Us" link to "Email us about this website"
