### ISSUE TITLE
migrate the code.gov API docs here

### ISSUE THREAD

**Issue by gbinal** [GSA/open-gsa-redesign#353]
https://github.com/GSA/open-gsa-redesign/blob/apidocs-codegov-08122019/_apidocs/codedotgov.md

To Do: 
* [ ] Decide on version number 
* [ ] Consider api.gsa.gov
* [ ] Consider implementing the endpoint design 
* [ ] Update the sample URL in the API key registration form (`exampleApiUrl`)
* [ ] Update the prose on the page 
* [ ] Make the swagger work
* [ ] Link to the correct openAPI spec file 
* [ ] what else?

cc @seanstar12

**Comment by vickimcfadden** [comment]
It looks like the [code.gov API has been archived](https://github.com/GSA/code-gov-api-client). Closing this issue.
