### ISSUE TITLE
CONTRIBUTING.md File is Incorrect

### ISSUE THREAD

**Issue by ctrimm** [GSA/open-gsa-redesign#404]
In the CONTRIBUTING.md file, it states `Submit contributions to https://github.com/GSA/open-gsa-redesign as pull requests to the dev branch.`.

However, there is no `dev` branch to be found in this repository.

My suggested fix is to make `dev` be `master` branch instead.

**Comment by jfredrickson5** [comment]
Thanks for catching that!
