### ISSUE TITLE
Review 18F list for any more APIs

### ISSUE THREAD

**Issue by rdgsa** [GSA/open-gsa-redesign#62]
See if any of the APIs on this list have not been added yet:

https://18f.gsa.gov/developer/

**Comment by rdgsa** [comment]
After review, these can be added to APIs list:

Discovery API
FOIA API
Hub API
18F Team API

Exclude these:
OpenFEC (not for GSA)

**Comment by KehindeOgundolie** [comment]
I am working on this issue

**Comment by KehindeOgundolie** [comment]
@rdgsa Hey Ryan, I need some clarification on the 18F Team API. Which one in particular is the 18F API on the link that you provided.

**Comment by KehindeOgundolie** [comment]
@rdgsa Can you provide some clarification on the issue above please?

**Comment by rdgsa** [comment]
I no longer see the 18F Team API so you can exclude this.

**Comment by KehindeOgundolie** [comment]
Okay this issue has been resolved.
