### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jamesmelville** [GSA/open-gsa-redesign#740]
The link on https://open.gsa.gov/api/perdiem to "Terms of Service for GSA.gov's Developer Resources" points at the URL https://www.gsa.gov/technology/government-it-initiatives/digital-strategy/terms-of-service-for-gsagovs-developer-resources, which results in an error page. 

https://github.com/GSA/open-gsa-redesign/blame/95c0e3da70523a9d28148805115ec1248073e595/_apidocs/perdiem.md#L11

**Comment by wqwales** [comment]
Do you all need help updating this?  Is this preventing pages from being published? or is it just a routine broken URL? 
If you need help publishing the correct URL pls provide the new one and Jeff or I can help with a PR if necessary.

@jfredrickson5  @CinnyaSm

**Comment by jfredrickson5** [comment]
@wqwales Just a routine broken URL. We should inform the Per Diem API owner, perhaps via CISS. The API owner should be able to update their docs. I'll fire off an email.

**Comment by jfredrickson5** [comment]
The Per Diem API team has fixed this. Thanks, @jamesmelville!
