### ISSUE TITLE
Exclusion Search Web Service Timeout

### ISSUE THREAD

**Issue by romanazimov** [GSA/open-gsa-redesign#786]
Before yesterday's update on sam.gov, I was able to use the webservice 'https://gw.sam.gov/SAMWS/1.0/ExclusionSearch' from http://gsa.github.io/openIAE/developer_resources/Using_SAM_web_services/

Did the new update break it?

This is my error:
[https://i.imgur.com/f0SMB2R.png](https://i.imgur.com/f0SMB2R.png)

**Comment by jfredrickson5** [comment]
Hi @romanazimov,

For issues with SAM web services, please contact the [Federal Service Desk](https://www.fsd.gov/). If the knowledge base there does not have your solution, you can open an incident or chat with the service desk.
