### ISSUE TITLE
Add redirect from /developer to

### ISSUE THREAD

**Issue by rdgsa** [GSA/open-gsa-redesign#79]
@saracope  There was an existing redirect from gsa.gov/developer, which I believe is a standard for agency developer hubs.

It was going to open.gsa.gov/developer --> open.gsa.gov/api. Now it returns a 404.

I believe we should redirect open.gsa.gov/developer --> the open.gsa.gov home page (not api as previously). Because the entire site is really the developer hub, not just the /api page.

**Comment by saracope** [comment]
Entered a ticket for that redirect, thanks!

**Comment by jcastle** [comment]
The link goes to the open.gsa.gov repo and should go to the open.gsa.gov site.

**Comment by saracope** [comment]
gsa.gov/developer forwards to the websites. It's gsa.gov/developers that is forwarding to the repo and there's a separate ticket for that. Closing this issue.
