### ISSUE TITLE
SERVER ERROR - Web Service is DOWN

### ISSUE THREAD

**Issue by pavlelozevski** [GSA/open-gsa-redesign#794]
We've been using this service for over 8 years and now it is down or something has changed!
Can you confirm that these two endpoints are still active or not:

- https://gw.sam.gov/SAMWS/1.0/ExclusionSearch

or this one

- https://gw.sam.gov/SAMW/1.0/ExclusionSearch

**Comment by jfredrickson5** [comment]
Hi @pavlelozevski,

Please contact the Federal Service Desk for assistance with any issues related to SAM APIs: https://www.fsd.gov/

**Comment by pavlelozevski** [comment]
Thanks @jfredrickson5
