### ISSUE TITLE
Add search module

### ISSUE THREAD

**Issue by jcastle** [GSA/open-gsa-redesign#8]

**Comment by jfredrickson5** [comment]
@saracope In this change, do you want to add a search box throughout the site such as in the nav bar? Or just have search functionality ready for the hackathon, at which point it'll be decided where such a search box goes?

**Comment by jfredrickson5** [comment]
Also, addition of the search module in PR #26 included adding the jekyll_pages_api gem in a new Gemfile. I'm not sure what the official bootstrapping process is for this project, but `bundle install` should now be part of it.

**Comment by jfredrickson5** [comment]
Added a project hypothesis regarding search. We will see about implementing a site-wide search box during the hackathon.
