### ISSUE TITLE
Broken Links For SAM APIs

### ISSUE THREAD

**Issue by SirNoobz768** [GSA/open-gsa-redesign#869]
All of the links to the SAM API documentation on https://open.gsa.gov/api are broken.  I believe the URLs are missing /api/ in the path.  For example, the link to Opportunity Management is:
https://open.gsa.gov/opportunities-api/
But it should be:
https://open.gsa.gov/api/opportunities-api/

**Comment by jfredrickson5** [comment]
Fixed in #870. Thank you!
